### ISSUE TITLE
Need demonstration or tutorial how to use "Set placements" tool 

### ISSUE THREAD

**Issue by drfenixion** [galou/freecad.cross#14]
I trying to use "Set placement" tool various ways but without any usefull result because I dont undastand how it works.
I cant use freecad.cross without this tool because not other way to change position of joint origin.
Need any demo or tutorial for this "Set placements" tool.
Also it is good to have visual tool like regular Transform (how we do with bodies in FreeCAD) for change origin of Joint.

**Comment by galou** [comment]
I totally agree with you that the tool is difficult to use and that a video tutorial is something that is missing. I'll try to find some time to create one.

In the meantime, you can use the three dots on the right of the "Origin" property to set the origin with a visual feedback (by clicking on "Apply").

I know a mean to use the regular Transform tool but it requires that the parameter is called "Placement". Now, the property is called "Origin" to fit the URDF jargon and the placement is the absolute joint position, a read-only property.

**Comment by drfenixion** [comment]
> In the meantime, you can use the three dots on the right of the "Origin" property to set the origin with a visual feedback (by clicking on "Apply").

Thanks, forgot about this option but with that way it will long job for big models to set all origins. it's also not convenient.

**Comment by drfenixion** [comment]
Added related issue [https://github.com/galou/freecad.cross/issues/21](https://github.com/galou/freecad.cross/issues/21)

**Comment by galou** [comment]
Cf. https://github.com/galou/freecad.cross/wiki/Command-SetPlacement

Please feel free to try it out and improve the documentation.

**Comment by drfenixion** [comment]
> Cf. https://github.com/galou/freecad.cross/wiki/Command-SetPlacement
> 
> Please feel free to try it out and improve the documentation.

Thank you. 

"Setting the MountedPlacement property of links" docs is ok.

But instructions "Setting the Origin of joints" does not clear for me. I was experimenting again and find only working way how to set origin to right position with "SetPlacement" command.
Working way is "select joint, select child link LCS (where it should be connected to parent link), select parent link LCS (where it should be connected to child link). After that child link will setted to the parent link LCS (for child link connection).

My worked result (child LCS established in parent LCS for child link as I wanted)  
![freecad_cross_joint_set_position](https://github.com/galou/freecad.cross/assets/13005708/9c5d514b-cdae-4ed8-aacb-2ce825adb913)



It nice to rewrite 2 lines from wiki with other words:

"a CROSS::Joint, the LCS of the parent link, and the LCS of the child link on the same link," - tryed that way does not give any usefull result. Looks i dont understand this way.

"a CROSS::Joint, the "child" LCS on the parent link, and the "parent" LCS on the child link." - it is does not clear and I understood this only after experimenting. Looks I did this way on screen.
