### ISSUE TITLE
Tips for usinkg CROSS for custom build ros with --symlink-install

### ISSUE THREAD

**Issue by sprhawk** [galou/freecad.cross#15]
I built `ROS2` under `debian bookworm` with `colcon build --symlink-install`

All the ros packages are installed in separate directory hierarchy , and `ros_workspace/install/setup.bash` will set `PYTHONPATH` for every packages. But because `FreeCAD` will erase environment variable  `PYTHONPATH` after startup,  I provide here a solution for that:

```
FreeCAD  -P ${PYTHONPATH//:/' -P '}
```

BTW: the required `libnglib` on `Debian Bookworm` is installed under /usr/lib/x86_64-linux-gnu/netgen, which is not found by FreeCAD. So I need to add
```
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/netgen:$LD_LIBRARY_PATH
```
to start FreeCAD + freecad.cross properly

**Comment by drfenixion** [comment]
Maybe you should add PR with TROUBLESHOOTING.md with short description of this case?
@galou, what do you think?

**Comment by galou** [comment]
I added a remark in the `README.md` file, cf f400ae4. Thanks!

**Comment by galou** [comment]
What is the nglib library required for?  Is it really required by CROSS because it's not installed on my system but CROSS obviously works?

**Comment by galou** [comment]
Maybe related to [this](https://forum.freecad.org/viewtopic.php?p=731355#p731355)?

**Comment by sprhawk** [comment]
> Maybe related to [this](https://forum.freecad.org/viewtopic.php?p=731355#p731355)?

My Debian just install `nglib` under a `netgen` subdir which cannot be found by FreeCAD

**Comment by galou** [comment]
If this is required by ROS, then `setup.bash` should set `$LD_LIBRARY_PATH` correctly. Isn't it the case?

**Comment by sprhawk** [comment]
> If this is required by ROS, then `setup.bash` should set `$LD_LIBRARY_PATH` correctly. Isn't it the case?

My bad. the netgen is required by FreeCAD,  not ROS
