### ISSUE TITLE
missing reload `joint_proxy`, `link_proxy`

### ISSUE THREAD

**Issue by sprhawk** [galou/freecad.cross#24]
https://github.com/galou/freecad.cross/blob/a138f1aa482b3da99e6ccb096891cf947f72e65a/freecad/cross/ui/command_reload.py#L26-L73

Are  `joint_proxy`, `link_proxy`  missing or there is some reason ?

**Comment by sprhawk** [comment]
@galou Hello, there is another `robot_proxy.py` also missing, fixed in my [latest commit](https://github.com/iotpi/freecad.cross/tree/fix-reload)

**Comment by galou** [comment]
Thanks, it was fixed since then as well as `xacro_object_proxy`.
