### ISSUE TITLE
Ask feature. Add bounding cylinder with radius equal length of most part of object from object center.

### ISSUE THREAD

**Issue by drfenixion** [galou/freecad.cross#30]
Idea is adding bounding cylinder for propeller for collision. May be there is should be option of cyllinder orientation if source object not a propeller and something other that should be simplifing to pipe.

**Comment by galou** [comment]
This is for sure a good idea but you probably don't need it. With CROSS, you normally design your parts at the origin and along one of the main axes. The collision part should be also at this location with this orientation (there is only one `MountedPlacement` property for links which must be valid for all 3 `Real`, `Visual` and `Collision` linked parts.

**Comment by drfenixion** [comment]
Closed by merge
