### ISSUE TITLE
New fork named OVERCROSS - includes launcher for Gazebo and inertia auto calc tool and others

### ISSUE THREAD

**Issue by drfenixion** [galou/freecad.cross#40]
### Created fork named OVERCROSS with new features:

1. Material selection of link or whole robot
2. Auto calculation of mass and inertia
3. Launcher for Gazebo
4. New some icons and icons reordering
5. Bug fixes
6. Others

[OVERCROSS](https://github.com/drfenixion/freecad.cross)

Tools of FreeCAD OVERCROSS
![Tools of FreeCAD OVERCROSS](https://github.com/galou/freecad.cross/assets/13005708/7fa4c8ab-9622-4400-9b07-dc55523791ab)
Launched Rviz and Gazebo from Gazebo launcher
![320291505-a46715a0-0dc6-4f6e-b80e-e4c644589477](https://github.com/galou/freecad.cross/assets/13005708/aeacf504-c0fb-404d-bd2a-0d42d35f4b97)
Generated inertia blocks and centers of mass in Gazebo
![320291446-d3d44e65-a9cc-45cc-937a-be5008b98608](https://github.com/galou/freecad.cross/assets/13005708/822665d4-03f8-4a00-ae30-25ca812c1960)

Many thanks to Galou for his great job on CROSS what was the basis for my work!

**Comment by galou** [comment]
You're welcome.

I would be interested in knowing your motivations (can be as PM).

Good luck for OVERCROSS and let's hope that we can still collaborate.
