### ISSUE TITLE
Hiding joint origins

### ISSUE THREAD

**Issue by topherbuckley** [galou/freecad.cross#44]
Is there any way to hide the giant joint origins? Standard visibility controls don't appear to work.

**Comment by drfenixion** [comment]
Click Robot -> View properties -> ROS Display -> Joint axis = size of it

**Comment by galou** [comment]
Similarly, you can toggle visibility and size of each joint axis individually by selecting a joint.

By the way, help is welcome to show the origin of links in the 3D view.
