### ISSUE TITLE
No module named 'geometry_msgs' at attempt to Get Planning Scene

### ISSUE THREAD

**Issue by Vladimat** [galou/freecad.cross#46]
`01:15:42  Running the Python command 'GetPlanningScene' failed:
Traceback (most recent call last):
  File "/home/xxxx/.local/share/FreeCAD/Mod/freecad.cross/freecad/cross/ui/command_get_planning_scene.py", line 33, in Activated
    fcgui.addModule('freecad.cross.planning_scene_proxy')

No module named 'geometry_msgs'`

Ubuntu 22.04 FreeCAD 1.0rc2

**Comment by galou** [comment]
The `GetPlanningScene` command requires ROS (`source setup.bash`). I'll deactivate the command when ROS is not detected.
