### ISSUE TITLE
Using fpo Preferences API to manage all Config Params

### ISSUE THREAD

**Issue by mnesarco** [galou/freecad.cross#48]
Hi @galou ,
Now that you are using fpo, I wonder if you have considered using the preferences API?

https://github.com/mnesarco/fcapi/blob/main/docs/documentation.md#freecad-preferences

I allows you to centralize all preferences management in a declarative way. Just let me know if you want to discuss about it.

**Comment by galou** [comment]
Yes I saw it but didn't add any parameter lately. It'd be to use it of course. Everything that simplifies the code is good. I'll probably do it next time I add a parameter.

**Comment by mnesarco** [comment]
Yeah I just realized that you have very few parameters. I am closing this because it is not a issue.
