### ISSUE TITLE
Redefinition of function cylinder_between_points

### ISSUE THREAD

**Issue by mnesarco** [galou/freecad.cross#53]
function `cylinder_between_points` is defined twice in module `coin_utils.py`. As python does not support function overloading, the last definition just overrides the former.

First definition: https://github.com/galou/freecad.cross/blob/a5d2dcf04ac31eb4caf41693bccc71ca9ce605bd/freecad/cross/coin_utils.py#L54

Last definition: https://github.com/galou/freecad.cross/blob/a5d2dcf04ac31eb4caf41693bccc71ca9ce605bd/freecad/cross/coin_utils.py#L229

**Comment by mnesarco** [comment]
Just to clarify, the PR #52 does not fix this issue.

**Comment by galou** [comment]
I noticed, thanks. Cf. 3d0be8eec1c9.
