### ISSUE TITLE
Current development repo (freecad.robotcad vs freecad.cross)

### ISSUE THREAD

**Issue by mnesarco** [galou/freecad.cross#54]
Hello @galou 
I recently found robotcad, and I wonder if all the development was moved there as it is a fork of this repo but with many more commits.

https://github.com/drfenixion/freecad.robotcad

Both projects seems to be actively maintained, what is the relation between the two?

**Comment by galou** [comment]
@drfenixion wanted faster code development. Now, his fork call an external server, which I don't want to integrate. He's integrating the features of this repo but I lack time to integrate his changes. There will probably be always two forks but we profit from each other's development.

**Comment by mnesarco** [comment]
Thank you for the info.
